/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openJpeg_OpenJPEGJavaDecoder */

#ifndef _Included_org_openJpeg_OpenJPEGJavaDecoder
#define _Included_org_openJpeg_OpenJPEGJavaDecoder
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_org_openJpeg_OpenJPEGJavaEncoder_internalDecodeImageToJ2K(JNIEnv *, jobject, jobjectArray);
JNIEXPORT jint JNICALL Java_org_openJpeg_OpenJPEGJavaDecoder_internalGetDecodeFormat(JNIEnv *env, jobject obj,jobjectArray javaParameters) ;

#ifdef __cplusplus
}
#endif
#endif
